# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ujjwal Gulecha
email: me@ujjwalgulecha.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineer at Anthropic passionate about scalable systems, algorithm design, and machine learning.
  Building innovative solutions to complex problems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ujjwalgulecha.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ujjwalgulecha
github_username: ujjwalgulecha
linkedin_username: ujjwalgulecha

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
author: Ujjwal Gulecha
lang: en_US

# Social defaults
social:
  name: Ujjwal Gulecha
  links:
    - https://twitter.com/ujjwalgulecha
    - https://github.com/ujjwalgulecha
    - https://linkedin.com/in/ujjwalgulecha

# Social media settings
twitter:
  username: ujjwalgulecha
  card: summary_large_image

# Logo for structured data
logo: /assets/images/social-card.svg

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Ujjwal Gulecha"
      image: /assets/images/social-card.svg
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      image: /assets/images/social-card.svg

# Markdown processor
markdown: kramdown
highlighter: rouge

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
